version: '3.8'

services:
  project:
    build:
      args:
        - WORKING_DIRECTORY
        - BUILDKIT_INLINE_CACHE
      cache_from:
        - ${IMAGE}
    image: ${IMAGE}
    working_dir: ${WORKING_DIRECTORY}
