ifndef PICARD_GITHUB_MODULE
PICARD_GITHUB_MODULE := 1
REGISTRY_HOSTNAME := ghcr.io
REGISTRY_NAMESPACE := $(GITHUB_REPOSITORY_OWNER)
REGISTRY_USERNAME := $(GITHUB_ACTOR)
REGISTRY_PASSWORD := $(GITHUB_TOKEN)
endif
