ifndef PICARD_LOG_MODULE
PICARD_LOG_MODULE := 1

PICARD_LOG_PREFIX := picard
PICARD_LOG_INFO = $(if $(PICARD_DEBUG),$(info $(NEWLINE)$(PICARD_LOG_PREFIX) [info]:$(NEWLINE)$1))
PICARD_LOG_WARNING = $(warning $(NEWLINE)$(PICARD_LOG_PREFIX) [warning]:$(NEWLINE)$1)
PICARD_LOG_ERROR = $(error $(NEWLINE)$(PICARD_LOG_PREFIX) [error]:$(NEWLINE)$1)

endif
